[workspace]
members = [
    "src/wrappers/themis/rust",
    "src/wrappers/themis/rust/libthemis-sys",
    "src/wrappers/themis/rust/libthemis-src",
]
default-members = [
    "src/wrappers/themis/rust",
]
