/*
** Inserted at beginning of c files generated by bison
** REMEMBER:  Change bison.reset too.
*/

/*@-allmacros@*/
/*@+boolint@*/
/*@+charint@*/
/*@-macroparams@*/
/*@-macroundef@*/
/*@-unreachable@*/
/*@-macrospec@*/
/*@-varuse@*/
/*@+ignorequals@*/
/*@-macrostmt@*/
/*@-noeffect@*/
/*@-shadow@*/
/*@-exitarg@*/
/*@-macroredef@*/
/*@-uniondef@*/
/*@-compdef@*/
/*@-matchfields@*/
/*@-exportlocal@*/
/*@-evalorderuncon@*/
/*@-exportheader@*/
/*@-typeuse@*/
/*@-redecl@*/
/*@-redef@*/
/*@-noparams@*/
/*@-ansireserved@*/
/*@-fielduse@*/
/*@-ifblock@*/
/*@-elseifcomplete@*/
/*@-whileblock@*/
/*@-forblock@*/
/*@-branchstate@*/
/*@-readonlytrans@*/
/*@-namechecks@*/
/*@-usedef@*/
/*@-systemunrecog@*/
/*@-dependenttrans@*/
/*@-unqualifiedtrans@*/
/*@-nullassign@*/
/*@-nullpass@*/
/*@-nullptrarith*/
/*@-usereleased@*/
/*@-declundef@*/

/*drl added 11/27/2001*/
/*@-bounds@*/

/*drl added 12/11/2002*/
/*@-type@*/

/* < end of bison.head > */

#ifndef BISON_MTGRAMMAR_TAB_H
# define BISON_MTGRAMMAR_TAB_H

#ifndef YYSTYPE
typedef union {
  mttok tok; 
  mtDeclarationNode mtdecl;
  mtDeclarationPiece mtpiece;
  mtDeclarationPieces mtpieces;
  mtContextNode mtcontext;
  mtValuesNode mtvalues;
  mtDefaultsNode mtdefaults;
  mtDefaultsDeclList mtdeflist;
  mtAnnotationsNode mtannotations;
  mtAnnotationList mtannotlist;
  mtAnnotationDecl mtannotdecl;
  mtMergeNode mtmerge;
  mtMergeItem mtmergeitem;
  mtMergeClauseList mtmergeclauselist;
  mtMergeClause mtmergeclause;
  mtTransferClauseList mttransferclauselist;
  mtTransferClause mttransferclause;
  mtTransferAction mttransferaction;
  mtLoseReferenceList mtlosereferencelist;
  mtLoseReference mtlosereference;
  pointers pointers;
  /*@only@*/ cstringList cstringlist;
  ctype ctyp;
  /*@only@*/ qtype qtyp;
  qual qual;
  qualList quals;
} yystype;
# define YYSTYPE yystype
# define YYSTYPE_IS_TRIVIAL 1
#endif
# define	MT_BADTOK	257
# define	MT_END	258
# define	MT_STATE	259
# define	MT_GLOBAL	260
# define	MT_CONTEXT	261
# define	MT_ONEOF	262
# define	MT_DEFAULTS	263
# define	MT_DEFAULT	264
# define	MT_REFERENCE	265
# define	MT_PARAMETER	266
# define	MT_RESULT	267
# define	MT_CLAUSE	268
# define	MT_LITERAL	269
# define	MT_NULL	270
# define	MT_ANNOTATIONS	271
# define	MT_ARROW	272
# define	MT_MERGE	273
# define	MT_TRANSFERS	274
# define	MT_PRECONDITIONS	275
# define	MT_POSTCONDITIONS	276
# define	MT_LOSEREFERENCE	277
# define	MT_AS	278
# define	MT_ERROR	279
# define	MT_PLUS	280
# define	MT_STAR	281
# define	MT_BAR	282
# define	MT_LPAREN	283
# define	MT_RPAREN	284
# define	MT_LBRACKET	285
# define	MT_RBRACKET	286
# define	MT_LBRACE	287
# define	MT_RBRACE	288
# define	MT_COMMA	289
# define	MT_CHAR	290
# define	MT_INT	291
# define	MT_FLOAT	292
# define	MT_DOUBLE	293
# define	MT_VOID	294
# define	MT_ANYTYPE	295
# define	MT_INTEGRALTYPE	296
# define	MT_UNSIGNEDINTEGRALTYPE	297
# define	MT_SIGNEDINTEGRALTYPE	298
# define	MT_CONST	299
# define	MT_VOLATILE	300
# define	MT_RESTRICT	301
# define	MT_STRINGLIT	302
# define	MT_IDENT	303


#endif /* not BISON_MTGRAMMAR_TAB_H */
/*
** Resets all flags in bison.head
*/


/*@=allmacros@*/
/*@=boolint@*/
/*@=charint@*/
/*@=macroparams@*/
/*@=macroundef@*/
/*@=unreachable@*/
/*@=macrospec@*/
/*@=varuse@*/
/*@=ignorequals@*/
/*@=macrostmt@*/
/*@=noeffect@*/
/*@=shadow@*/
/*@=exitarg@*/
/*@=macroredef@*/
/*@=uniondef@*/
/*@=compdef@*/
/*@=matchfields@*/
/*@=exportlocal@*/
/*@=evalorderuncon@*/
/*@=exportheader@*/
/*@=typeuse@*/
/*@=redecl@*/
/*@=redef@*/
/*@=noparams@*/
/*@=ansireserved@*/
/*@=fielduse@*/
/*@=ifblock@*/
/*@=elseifcomplete@*/
/*@=whileblock@*/
/*@=forblock@*/
/*@=branchstate@*/
/*@=readonlytrans@*/
/*@=namechecks@*/
/*@=usedef@*/
/*@=systemunrecog@*/
/*@=dependenttrans@*/
/*@=unqualifiedtrans@*/
/*@=declundef@*/


/*drl added 11/27/2001*/
/*@=bounds@*/

/*drl added 12/11/2002*/
/*@=type@*/
