/*
** Inserted at beginning of c files generated by bison
** REMEMBER:  Change bison.reset too.
*/

/*@-allmacros@*/
/*@+boolint@*/
/*@+charint@*/
/*@-macroparams@*/
/*@-macroundef@*/
/*@-unreachable@*/
/*@-macrospec@*/
/*@-varuse@*/
/*@+ignorequals@*/
/*@-macrostmt@*/
/*@-noeffect@*/
/*@-shadow@*/
/*@-exitarg@*/
/*@-macroredef@*/
/*@-uniondef@*/
/*@-compdef@*/
/*@-matchfields@*/
/*@-exportlocal@*/
/*@-evalorderuncon@*/
/*@-exportheader@*/
/*@-typeuse@*/
/*@-redecl@*/
/*@-redef@*/
/*@-noparams@*/
/*@-ansireserved@*/
/*@-fielduse@*/
/*@-ifblock@*/
/*@-elseifcomplete@*/
/*@-whileblock@*/
/*@-forblock@*/
/*@-branchstate@*/
/*@-readonlytrans@*/
/*@-namechecks@*/
/*@-usedef@*/
/*@-systemunrecog@*/
/*@-dependenttrans@*/
/*@-unqualifiedtrans@*/
/*@-nullassign@*/

/* < end of bison.head > */

typedef union
{
 lltok tok;
 int count;
 specialClauseKind sck;
 qual typequal;
 qualList tquallist;
 ctype ctyp;
 sRef sr;
 /*@only@*/ qtype qtyp;
 /*@only@*/ cstring cname;
 /*@only@*/ idDecl ntyp;
 /*@only@*/ idDeclList ntyplist;
 /*@only@*/ uentryList flist;
 /*@owned@*/ uentryList entrylist;
 /*@observer@*/ /*@dependent@*/ uentry entry;
 /*@only@*/ uentry oentry;
 /*@only@*/ exprNode expr;
 /*@only@*/ enumNameList enumnamelist;
 /*@only@*/ exprNodeList alist;
 /*@only@*/ sRefSet srset; 
} YYSTYPE;
#define	BADTOK	258
#define	SKIPTOK	259
#define	CTOK_ELIPSIS	260
#define	CASE	261
#define	DEFAULT	262
#define	CIF	263
#define	CELSE	264
#define	SWITCH	265
#define	WHILE	266
#define	DO	267
#define	CFOR	268
#define	GOTO	269
#define	CONTINUE	270
#define	BREAK	271
#define	RETURN	272
#define	TSEMI	273
#define	TLBRACE	274
#define	TRBRACE	275
#define	TCOMMA	276
#define	TCOLON	277
#define	TASSIGN	278
#define	TLPAREN	279
#define	TRPAREN	280
#define	TLSQBR	281
#define	TRSQBR	282
#define	TDOT	283
#define	TAMPERSAND	284
#define	TEXCL	285
#define	TTILDE	286
#define	TMINUS	287
#define	TPLUS	288
#define	TMULT	289
#define	TDIV	290
#define	TPERCENT	291
#define	TLT	292
#define	TGT	293
#define	TCIRC	294
#define	TBAR	295
#define	TQUEST	296
#define	CSIZEOF	297
#define	ARROW_OP	298
#define	CTYPEDEF	299
#define	COFFSETOF	300
#define	INC_OP	301
#define	DEC_OP	302
#define	LEFT_OP	303
#define	RIGHT_OP	304
#define	LE_OP	305
#define	GE_OP	306
#define	EQ_OP	307
#define	NE_OP	308
#define	AND_OP	309
#define	OR_OP	310
#define	MUL_ASSIGN	311
#define	DIV_ASSIGN	312
#define	MOD_ASSIGN	313
#define	ADD_ASSIGN	314
#define	SUB_ASSIGN	315
#define	LEFT_ASSIGN	316
#define	RIGHT_ASSIGN	317
#define	AND_ASSIGN	318
#define	XOR_ASSIGN	319
#define	OR_ASSIGN	320
#define	CSTRUCT	321
#define	CUNION	322
#define	CENUM	323
#define	VA_ARG	324
#define	VA_DCL	325
#define	QGLOBALS	326
#define	QMODIFIES	327
#define	QNOMODS	328
#define	QCONSTANT	329
#define	QITER	330
#define	QDEFINES	331
#define	QUSES	332
#define	QALLOCATES	333
#define	QSETS	334
#define	QRELEASES	335
#define	QPRECLAUSE	336
#define	QPOSTCLAUSE	337
#define	QALT	338
#define	QUNDEF	339
#define	QKILLED	340
#define	QENDMACRO	341
#define	LLMACRO	342
#define	LLMACROITER	343
#define	LLMACROEND	344
#define	TENDMACRO	345
#define	QSWITCHBREAK	346
#define	QLOOPBREAK	347
#define	QINNERBREAK	348
#define	QSAFEBREAK	349
#define	QINNERCONTINUE	350
#define	QFALLTHROUGH	351
#define	QLINTNOTREACHED	352
#define	QLINTFALLTHROUGH	353
#define	QLINTFALLTHRU	354
#define	QARGSUSED	355
#define	QPRINTFLIKE	356
#define	QLINTPRINTFLIKE	357
#define	QSCANFLIKE	358
#define	QMESSAGELIKE	359
#define	QNOTREACHED	360
#define	QCONST	361
#define	QVOLATILE	362
#define	QINLINE	363
#define	QEXTENSION	364
#define	QEXTERN	365
#define	QSTATIC	366
#define	QAUTO	367
#define	QREGISTER	368
#define	QOUT	369
#define	QIN	370
#define	QYIELD	371
#define	QONLY	372
#define	QTEMP	373
#define	QSHARED	374
#define	QREF	375
#define	QUNIQUE	376
#define	QCHECKED	377
#define	QUNCHECKED	378
#define	QCHECKEDSTRICT	379
#define	QCHECKMOD	380
#define	QKEEP	381
#define	QKEPT	382
#define	QPARTIAL	383
#define	QSPECIAL	384
#define	QOWNED	385
#define	QDEPENDENT	386
#define	QRETURNED	387
#define	QEXPOSED	388
#define	QNULL	389
#define	QOBSERVER	390
#define	QISNULL	391
#define	QEXITS	392
#define	QMAYEXIT	393
#define	QNEVEREXIT	394
#define	QTRUEEXIT	395
#define	QFALSEEXIT	396
#define	QLONG	397
#define	QSIGNED	398
#define	QUNSIGNED	399
#define	QSHORT	400
#define	QUNUSED	401
#define	QSEF	402
#define	QNOTNULL	403
#define	QRELNULL	404
#define	QABSTRACT	405
#define	QCONCRETE	406
#define	QMUTABLE	407
#define	QIMMUTABLE	408
#define	QTRUENULL	409
#define	QFALSENULL	410
#define	QEXTERNAL	411
#define	QREFCOUNTED	412
#define	QREFS	413
#define	QNEWREF	414
#define	QTEMPREF	415
#define	QKILLREF	416
#define	QRELDEF	417
#define	CGCHAR	418
#define	CBOOL	419
#define	CINT	420
#define	CGFLOAT	421
#define	CDOUBLE	422
#define	CVOID	423
#define	QANYTYPE	424
#define	QINTEGRALTYPE	425
#define	QUNSIGNEDINTEGRALTYPE	426
#define	QSIGNEDINTEGRALTYPE	427
#define	IDENTIFIER	428
#define	NEW_IDENTIFIER	429
#define	CCONSTANT	430
#define	ITER_NAME	431
#define	ITER_ENDNAME	432
#define	TYPE_NAME	433
#define	TYPE_NAME_OR_ID	434


extern YYSTYPE yylval;
/*
** Resets all flags in bison.head
*/


/*@=allmacros@*/
/*@=boolint@*/
/*@=charint@*/
/*@=macroparams@*/
/*@=macroundef@*/
/*@=unreachable@*/
/*@=macrospec@*/
/*@=varuse@*/
/*@=ignorequals@*/
/*@=macrostmt@*/
/*@=noeffect@*/
/*@=shadow@*/
/*@=exitarg@*/
/*@=macroredef@*/
/*@=uniondef@*/
/*@=compdef@*/
/*@=matchfields@*/
/*@=exportlocal@*/
/*@=evalorderuncon@*/
/*@=exportheader@*/
/*@=typeuse@*/
/*@=redecl@*/
/*@=redef@*/
/*@=noparams@*/
/*@=ansireserved@*/
/*@=fielduse@*/
/*@=ifblock@*/
/*@=elseifcomplete@*/
/*@=whileblock@*/
/*@=forblock@*/
/*@=branchstate@*/
/*@=readonlytrans@*/
/*@=namechecks@*/
/*@=usedef@*/
/*@=systemunrecog@*/
/*@=dependenttrans@*/
/*@=unqualifiedtrans@*/
