/*
** Inserted at beginning of c files generated by bison
** REMEMBER:  Change bison.reset too.
*/

/*@-allmacros@*/
/*@+boolint@*/
/*@+charint@*/
/*@-macroparams@*/
/*@-macroundef@*/
/*@-unreachable@*/
/*@-macrospec@*/
/*@-varuse@*/
/*@+ignorequals@*/
/*@-macrostmt@*/
/*@-noeffect@*/
/*@-shadow@*/
/*@-exitarg@*/
/*@-macroredef@*/
/*@-uniondef@*/
/*@-compdef@*/
/*@-matchfields@*/
/*@-exportlocal@*/
/*@-evalorderuncon@*/
/*@-exportheader@*/
/*@-typeuse@*/
/*@-redecl@*/
/*@-redef@*/
/*@-noparams@*/
/*@-ansireserved@*/
/*@-fielduse@*/
/*@-ifblock@*/
/*@-elseifcomplete@*/
/*@-whileblock@*/
/*@-forblock@*/
/*@-branchstate@*/
/*@-readonlytrans@*/
/*@-namechecks@*/
/*@-usedef@*/
/*@-systemunrecog@*/
/*@-dependenttrans@*/
/*@-unqualifiedtrans@*/
/*@-nullassign@*/
/*@-nullpass@*/
/*@-nullptrarith*/
/*@-usereleased@*/
/*@-declundef@*/

/*drl added 11/27/2001*/
/*@-bounds@*/

/*drl added 12/11/2002*/
/*@-type@*/

/*@-enummemuse@*/

/* < end of bison.head > */

/* A Bison parser, made by GNU Bison 2.3.  */

/* Skeleton interface for Bison's Yacc-like parsers in C

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     LST_SIMPLEID = 258,
     LST_LOGICALOP = 259,
     LST_EQOP = 260,
     LST_SIMPLEOP = 261,
     LST_MAPSYM = 262,
     LST_FIELDMAPSYM = 263,
     LST_MARKERSYM = 264,
     LST_ifTOKEN = 265,
     LST_thenTOKEN = 266,
     LST_elseTOKEN = 267,
     LST_LBRACKET = 268,
     LST_RBRACKET = 269,
     LST_SELECTSYM = 270,
     LST_SEPSYM = 271,
     LST_OPENSYM = 272,
     LST_CLOSESYM = 273,
     LST_COLON = 274,
     LST_COMMA = 275,
     LST_EOL = 276,
     LST_COMMENTSYM = 277,
     LST_WHITESPACE = 278,
     LST_QUANTIFIERSYM = 279,
     LST_EQUATIONSYM = 280,
     LST_EQSEPSYM = 281,
     LST_COMPOSESYM = 282,
     LST_LPAR = 283,
     LST_RPAR = 284,
     LST_assertsTOKEN = 285,
     LST_assumesTOKEN = 286,
     LST_byTOKEN = 287,
     LST_convertsTOKEN = 288,
     LST_enumerationTOKEN = 289,
     LST_equationsTOKEN = 290,
     LST_exemptingTOKEN = 291,
     LST_forTOKEN = 292,
     LST_generatedTOKEN = 293,
     LST_impliesTOKEN = 294,
     LST_includesTOKEN = 295,
     LST_introducesTOKEN = 296,
     LST_ofTOKEN = 297,
     LST_partitionedTOKEN = 298,
     LST_traitTOKEN = 299,
     LST_tupleTOKEN = 300,
     LST_unionTOKEN = 301,
     LST_BADTOKEN = 302
   };
#endif
/* Tokens.  */
#define LST_SIMPLEID 258
#define LST_LOGICALOP 259
#define LST_EQOP 260
#define LST_SIMPLEOP 261
#define LST_MAPSYM 262
#define LST_FIELDMAPSYM 263
#define LST_MARKERSYM 264
#define LST_ifTOKEN 265
#define LST_thenTOKEN 266
#define LST_elseTOKEN 267
#define LST_LBRACKET 268
#define LST_RBRACKET 269
#define LST_SELECTSYM 270
#define LST_SEPSYM 271
#define LST_OPENSYM 272
#define LST_CLOSESYM 273
#define LST_COLON 274
#define LST_COMMA 275
#define LST_EOL 276
#define LST_COMMENTSYM 277
#define LST_WHITESPACE 278
#define LST_QUANTIFIERSYM 279
#define LST_EQUATIONSYM 280
#define LST_EQSEPSYM 281
#define LST_COMPOSESYM 282
#define LST_LPAR 283
#define LST_RPAR 284
#define LST_assertsTOKEN 285
#define LST_assumesTOKEN 286
#define LST_byTOKEN 287
#define LST_convertsTOKEN 288
#define LST_enumerationTOKEN 289
#define LST_equationsTOKEN 290
#define LST_exemptingTOKEN 291
#define LST_forTOKEN 292
#define LST_generatedTOKEN 293
#define LST_impliesTOKEN 294
#define LST_includesTOKEN 295
#define LST_introducesTOKEN 296
#define LST_ofTOKEN 297
#define LST_partitionedTOKEN 298
#define LST_traitTOKEN 299
#define LST_tupleTOKEN 300
#define LST_unionTOKEN 301
#define LST_BADTOKEN 302




#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE

{
  ltoken ltok;  /* a leaf is also an ltoken */
  unsigned int count;
  /*@only@*/  ltokenList ltokenList;
  /*@only@*/  opFormNode opform;
  /*@owned@*/ sigNode signature;
  /*@only@*/  nameNode name;
  /*@owned@*/ lslOp operator;
  /*@only@*/  lslOpList operators;
  /*@-redef@*/ /*@-matchfields@*/ 
}
/* Line 1529 of yacc.c.  */

	YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif



/*
** Resets all flags in bison.head
*/


/*@=allmacros@*/
/*@=boolint@*/
/*@=charint@*/
/*@=macroparams@*/
/*@=macroundef@*/
/*@=unreachable@*/
/*@=macrospec@*/
/*@=varuse@*/
/*@=ignorequals@*/
/*@=macrostmt@*/
/*@=noeffect@*/
/*@=shadow@*/
/*@=exitarg@*/
/*@=macroredef@*/
/*@=uniondef@*/
/*@=compdef@*/
/*@=matchfields@*/
/*@=exportlocal@*/
/*@=evalorderuncon@*/
/*@=exportheader@*/
/*@=typeuse@*/
/*@=redecl@*/
/*@=redef@*/
/*@=noparams@*/
/*@=ansireserved@*/
/*@=fielduse@*/
/*@=ifblock@*/
/*@=elseifcomplete@*/
/*@=whileblock@*/
/*@=forblock@*/
/*@=branchstate@*/
/*@=readonlytrans@*/
/*@=namechecks@*/
/*@=usedef@*/
/*@=systemunrecog@*/
/*@=dependenttrans@*/
/*@=unqualifiedtrans@*/
/*@=declundef@*/


/*drl added 11/27/2001*/
/*@=bounds@*/

/*drl added 12/11/2002*/
/*@=type@*/

/*@=enummemuse@*/
