source 'https://github.com/CocoaPods/Specs.git'
source 'https://ph.cossacklabs.com/diffusion/CPDS/'

platform :ios, '8.2'
xcodeproj 'ThemisTest/ThemisTest.xcodeproj'
inhibit_all_warnings!

target :"ThemisTest" do

  pod 'themis'

  # stanfy
  pod 'SFCoreUtils', :git => 'https://github.com/stanfy/SFCoreUtils.git', :tag => '0.1.10'

  # RAC
  pod 'ReactiveCocoa', '~> 2.4.7'

  # nimbus
  pod 'AFNetworking', '~> 2.5.2'

end

post_install do |installer_representation|
	installer_representation.project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
			config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'LIBRESSL'
		end
	end
end