#
# Copyright (c) 2015 Cossack Labs Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

source 'https://github.com/CocoaPods/Specs.git'
source 'https://ph.cossacklabs.com/diffusion/CPDS/'

platform :ios, '8.2'
xcodeproj 'ThemisTest/ThemisTest.xcodeproj'
inhibit_all_warnings!

target :"ThemisTest" do

  pod 'themis'

  # stanfy
  pod 'SFCoreUtils', :git => 'https://github.com/stanfy/SFCoreUtils.git', :tag => '0.1.10'

  # RAC
  pod 'ReactiveCocoa', '~> 2.4.7'

  # nimbus
  pod 'AFNetworking', '~> 2.5.2'

end