/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_themis_example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appDoesNotThrow() {
        App classUnderTest = new App();
        assertDoesNotThrow(() -> App.encryptDataForStoring(), "encryptDataForStoring() should run without exceptions");
        assertDoesNotThrow(() -> App.encryptDataForMessaging(), "encryptDataForMessaging() should run without exceptions");
    }
}


