name: JsThemis

on:
  pull_request:
    paths:
      - '.github/workflows/test-nodejs.yaml'
      - 'docs/examples/js/**'
      - 'src/soter/**'
      - 'src/themis/**'
      - 'src/wrappers/themis/jsthemis/**'
      - 'test/jsthemis/**'
      - '**/*.mk'
      - 'Makefile'
      - '!**/README*'
  push:
    branches:
      - master
      - stable
      - release/*
  schedule:
    - cron: '0 6 * * *' # every day at 6:00 UTC

env:
  WITH_FATAL_WARNINGS: yes

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo sh -c 'echo "DEBIAN_FRONTEND=noninteractive" >> /etc/environment'
          sudo apt update
          sudo apt install --yes gcc make libssl-dev
      - name: Install Node.js via NVM
        run: |
          # Install latest NVM as described in documentation:
          # https://github.com/nvm-sh/nvm
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          source $HOME/.nvm/nvm.sh
          nvm install v8  # old LTS
          nvm install v10 # current LTS
          nvm install v12 # current stable
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install Themis Core
        run: |
          make
          sudo make install
          make prepare_tests_all
      - name: Run test suite (Node.js v8, maintenance)
        if: always()
        run: |
          source $HOME/.nvm/nvm.sh
          nvm use v8
          rm -rf node_modules package-lock.json
          make jsthemis_install
          make test_js
      - name: Run test suite (Node.js v10, LTS)
        if: always()
        run: |
          source $HOME/.nvm/nvm.sh
          nvm use v10
          rm -rf node_modules package-lock.json
          make jsthemis_install
          make test_js
      - name: Run test suite (Node.js v12, stable)
        if: always()
        run: |
          source $HOME/.nvm/nvm.sh
          nvm use v12
          rm -rf node_modules package-lock.json
          make jsthemis_install
          make test_js

  examples:
    name: Code examples
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo sh -c 'echo "DEBIAN_FRONTEND=noninteractive" >> /etc/environment'
          sudo apt update
          sudo apt install --yes gcc make libssl-dev
      - name: Install Node.js via NVM
        run: |
          # Install latest NVM as described in documentation:
          # https://github.com/nvm-sh/nvm
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          source $HOME/.nvm/nvm.sh
          nvm install v10 # current LTS
          nvm use v10
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install Themis Core
        run: |
          make
          sudo make install
      - name: Install JsThemis (Node.js v10, LTS)
        run: |
          source $HOME/.nvm/nvm.sh
          # Install JsThemis
          rm -rf node_modules package-lock.json
          make jsthemis_install
      - name: Test examples (Secure Cell)
        if: always()
        run: |
          source $HOME/.nvm/nvm.sh
          cd $GITHUB_WORKSPACE/docs/examples/js
          echo "Test Secure Cell..."
          enc=$(node secure_cell.js enc password message)
          dec=$(node secure_cell.js dec password "$enc")
          test "$dec" = "message"
          echo "ok"
      - name: Test examples (Secure Message)
        if: always()
        run: |
          source $HOME/.nvm/nvm.sh
          cd $GITHUB_WORKSPACE/docs/examples/js
          echo "Test Secure Message..."
          alice=($(node secure_keygen.js | cut -c 15-))
          bob=($(node secure_keygen.js | cut -c 15-))
          enc=$(node secure_message.js enc "${alice[0]}" "${bob[1]}" message)
          dec=$(node secure_message.js dec "${bob[0]}" "${alice[1]}" "$enc")
          test "$dec" = "message"
          echo "ok"
      - name: Test examples (Secure Session)
        if: always()
        run: |
          source $HOME/.nvm/nvm.sh
          cd $GITHUB_WORKSPACE/docs/examples/js
          echo "Test Secure Session..."
          node secure_session_server.js &
          sleep 1 # give the server time to launch
          node secure_session_client.js > output.txt
          kill -SIGTERM "$!"
          grep -q 'Hello server!!!' output.txt
          echo "ok"
      - name: Test examples (Secure Comparator)
        if: always()
        run: |
          source $HOME/.nvm/nvm.sh
          cd $GITHUB_WORKSPACE/docs/examples/js
          echo "Test Secure Comparator..."
          node secure_comparator_server.js &
          sleep 1 # give the server time to launch
          node secure_comparator_client.js
          kill -SIGTERM "$!"
          echo "ok"
