name: JsThemisOpenSSL3

on:
  pull_request:
    paths:
      - '.github/workflows/test-nodejs-openssl3.yaml'
      - 'docs/examples/js/**'
      - 'docs/examples/ts/**'
      - 'src/soter/**'
      - 'src/themis/**'
      - 'src/wrappers/themis/jsthemis/**'
      - 'test/jsthemis/**'
      - '**/*.mk'
      - 'Makefile'
      - '!**/README*'
  push:
    branches:
      - master
      - stable
      - release/*
  schedule:
    - cron: '*/5 * * * *' # test for every 5 minutes
  workflow_dispatch:

env:
  WITH_FATAL_WARNINGS: yes
  OPENSSL_VERSION: 3.0.10
  OPENSSL_PREFIX: /opt/openssl-3.0.10

jobs:
  unit-tests:
    name: Unit tests with OpenSSL 3
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
      fail-fast: false
    steps:
      - name: Install system dependencies
        run: |
          sudo sh -c 'echo "DEBIAN_FRONTEND=noninteractive" >> /etc/environment'
          sudo apt update
          sudo apt install -y git wget npm gcc make tar
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Compile OpenSSL 3.0.10
        run: |
          wget https://www.openssl.org/source/openssl-${{ env.OPENSSL_VERSION }}.tar.gz &&
          apt purge -y openssl  && \
          mkdir ${{ env.OPENSSL_PREFIX }} -p && \
          tar xf openssl-${{ env.OPENSSL_VERSION }}.tar.gz && \
          cd openssl-${{ env.OPENSSL_VERSION }} && \
          ./Configure --prefix=${{ env.OPENSSL_PREFIX }} && \
          make && \
          make install

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Themis Core
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          make
          sudo -E make install
      - name: Run test suite
        run: |
          echo Node.js: $(node --version)
          echo npm: $(npm --version)
          make test_js
